name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test the code
        run: |
          tox &> out.txt
          echo "::set-env name=PASSING::$([ $? == 0 ] && echo -n passing || echo -n failed)"
          echo "::set-env name=PASSING_ERR::$([ env.PASSING == "passing" ] && echo -n true || echo -n false)"
          echo "::set-env name=COVERAGE::$(grep TOTAL out.txt | awk '{print $4}' | tr -d '%\n')"
          echo "::set-env name=RELEASE_VERSION::$(grep version healthcheck_python/release.py | awk '{print $3}' | tr -d \''\n')"
      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 07e196561fb7496e619da3ef402209a6
          filename: coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          color: green
      - name: Create Comments-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 07e196561fb7496e619da3ef402209a6
          filename: passing.json
          label: test
          message: ${{ env.PASSING }}
          color: green
          isError: ${{ env.PASSING_ERR }}
      - name: Create pypi version badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 07e196561fb7496e619da3ef402209a6
          filename: version.json
          label: pypi
          message: v${{ env.RELEASE_VERSION }}
          color: blue
